# Generated by Django 3.1.5 on 2021-01-06 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=200)),
                ('valid', models.BooleanField(default=True)),
                ('created', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name_plural': 'Coins',
            },
        ),
        migrations.CreateModel(
            name='CoinMarketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valid', models.BooleanField(default=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptocurrencies.coin')),
            ],
        ),
    ]
