# Generated by Django 3.1.5 on 2021-01-06 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0003_auto_20210106_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinData',
            fields=[
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cryptocurrencies.coin')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('direct_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('top_tier_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('valid', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Coin Market Data',
            },
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coin',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='CoinMarketData',
        ),
    ]
