# Generated by Django 3.1.5 on 2021-01-06 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0004_auto_20210106_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coindata',
            options={'verbose_name_plural': 'Coin Data'},
        ),
        migrations.RemoveField(
            model_name='coin',
            name='created',
        ),
        migrations.AddField(
            model_name='coin',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 17, 46, 15, 642438, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='coindata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 17, 46, 15, 673678, tzinfo=utc), verbose_name='date created'),
        ),
    ]
