# Generated by Django 3.1.5 on 2021-01-07 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0005_auto_20210106_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='coindata',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
